### ISSUE TITLE
How to use WindowSpy ?

### ISSUE THREAD

**Issue by ellyx13** [CodeXTF2/WindowSpy#1] opened 2023-05-06 16:02 UTC
Hi sir, I'm a newbie. I was able to load the script, but when I run the window hunter command on the beacon (Windows 11 x64), I get the following error:
[!] Function call &beacon_inline_execute failed: The BOF content (arg 2) is empty. Did you read the right file? at WindowSpy.cna:54

Can you help me, please?

**Comment by CodeXTF2** [comment] 2023-05-06 16:23
Hi, I think I found the issue. Give me a moment to patch it. sry forgot to change a variable lol

**Comment by CodeXTF2** [comment] 2023-05-06 16:26
Ok. fixed it. forgot I decided on a name change halfway lol. Command should be "windowspy" now, and should work as intended. Fixed in 89d280a1ac457b93078bf2ed0e0e2bacb5fa60a5

**Comment by CodeXTF2** [comment] 2023-05-06 16:46
Ok, fixed in 70d021252db517cf20e36187dd78f29f50c4395f and tested to be working (for me at least). Do note that you dont need to run any commands (I have removed the windowhunter command to avoid confusion, it was used for testing purposes, my bad). The script automatically runs the BOF on every beacon checkin, performing your surveillance actions if any valid targets are detected.

**Comment by ellyx13** [comment] 2023-05-07 08:07
I downloaded the latest version but still get this error:
[04:05:48] [!] Function call &beacon_inline_execute failed: The BOF content (arg 2) is empty. Did you read the right file? at WindowSpy.cna:71
![image](https://user-images.githubusercontent.com/42670522/236665608-29a493c5-3e89-4c6c-9c3a-ba590fa7d15f.png)

**Comment by CodeXTF2** [comment] 2023-05-07 08:16
are you sure you re pulled? I have tested the  cna yesterday after fixing the bug. try opening a file named something like confidential.txt and see if it triggers a screenshot?

**Comment by CodeXTF2** [comment] 2023-05-07 08:18
also check if the .obj files are in the same folder as the .cna, WindowSpy.x64.obj and WindowSpy.x86.obj respectively

**Comment by ellyx13** [comment] 2023-05-07 13:46
My bad, I left the .cna file not in the same path as the .obj file. Your script worked, thank you

**Comment by CodeXTF2** [comment] 2023-05-07 13:48
Ok, nice. closing issue.

**Closed as completed** 2023-05-07 13:48 UTC
